#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/consolehelp/consolehelp /usr/bin/consolehelp

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/consolehelp.service ]; then
			rm /etc/systemd/system/consolehelp.service /usr/lib/systemd/system/consolehelp.service /usr/lib/systemd/user/consolehelp.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/consolehelp/files/systemd/consolehelp.service /usr/lib/systemd/system/consolehelp.service
		# try fix error in Ubuntu 18.04
		# Failed to reload consolehelp.service: Unit consolehelp.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/consolehelp.service:10: Executable path is not absolute: pkill -f "consolehelp --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/consolehelp.service
		fi
		systemctl daemon-reload
		systemctl enable consolehelp
		systemctl start consolehelp
	fi
fi
